#Demo of importing a GKE cluster into a given composition 
apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: cluster-1 # name to call the cluster in Cloud Resource Accelerator
spec:
  compositionRef:
    name: import-gcp-gke  # Possible values import-gcp-gke, import-aws-eks, import-azure-aks
  parameters:
   # managementPolicy: ObserveOnly #toggle to remove management
    clusterName: cluster-1 # name of the cluster in given cloud
    location: "us-central1-c"	# location of the cluster in given cloud
    #AWS EKS specifics below, leave blank if not using EKS
    securityGroupIds:
    - sg-0fd # security group of EKS cluster
    roleArn: arn:aws:iam # used for importing EKS
    subnetIds: #subnetIds used in EKS cluster
    - subnet-0
    - subnet-1 
    - subnet-2
    #Azure specifics below, leave blank if not using AKS
    resourceGroup: abc
