#example claim to build a node pool/group
apiVersion: demo.anthos.com/v1
kind: NodePool
metadata:
  name: gkenodepool
spec:
  compositionRef:
    name: gcp-node-pool # Possible values gcp-node-pool, aws-eks-nodegroup, azure-aks-nodepool
  parameters:
    # managementPolicy: ObserveOnly
    clusterName: "cluster-1"
    nodePoolName: "pool4" # name of the nodepool
    location: "us-central1-c"	
    nodeSize: medium  # Possible values small, medium, large
    minNodeCount: 1
    #AWS EKS specifics below, leave blank if not using EKS
    nodeRoleArn: arn:aws:iam:: # nodeRoleArn
    desiredSize: 2
    maxSize: 3
    subnetIds: #subnetIds used in EKS cluster
    - subnet-0 
    - subnet-1
    - subnet-2
