apiVersion: container.gcp.gke.cloud.google.com/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: cluster-1 # name of gke cluster
  name: cluster-1 # name of gke cluster
spec:
  providerConfigRef: 
    name: default-gcp # replace with provider
  forProvider:
    initialNodeCount: 1
    location: us-central1-c # add gcp region 
    minMasterVersion: "1.26"
   # removeDefaultNodePool: true
